language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.6
  - pypy

matrix:
  allow_failures:
    - python: pypy  # PyPy doesn't have _curses.

install:
  - pip install -q nose
  - python setup.py install

script:
  - nosetests -w /tmp blessings.tests
